services:
  rabbitmq:
    ports:
      - "5672:5672"
      - "15672:15672"

  kms-service-migrate:
    build: .
    env_file: .env

  kms-service:
    build: .
    env_file: .env
    ports:
      - "8000:8000"

  kms-service_db:
    ports:
      - "5430:5432"
